name: nsa_app
description: NSA Fitness Center App
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.11
  icons_launcher: ^2.1.3
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true